{
  "userName": "alex_viktorov",
  "userDetails": {
    "password": "superSecretPassword123",
    "mfaEnabled": false
  },
  "userInfo": {
    "firstName": "Alexander",
    "lastName": "VIKTOROV",
    "email": "alex****@soaesps.com",
    "telephone": "+7999********"
  }
}
