/**The MIT License (MIT)
 Copyright (c) 2018 by AleksanderSergeevich
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 */
package com.soaesps.core.DataModels.security;

import com.soaesps.core.DataModels.BaseEntity;
import com.soaesps.core.Utils.DateTimeHelper;
import com.soaesps.core.Utils.HashGeneratorHelper;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonValue;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import jakarta.persistence.*;

import java.io.ObjectStreamField;
import java.io.Serializable;
import java.time.Duration;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.*;

@Entity
@Table(name = "ISSUED_ACCESS_TOKENS")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class BaseOAuth2AccessToken extends BaseEntity implements Serializable {
    @Transient
    private int counter; // this need for checking number of requests during current session

    @Transient
    private String question; // this generated by IAutoEncoder

    @Transient
    private String answear; // this generated by IAutoEncoder

    @Column(name = "acc_token_value", length = 500, nullable = false)
    private String value;

    @Column(name = "acc_token_exp_date", nullable = false)
    private Instant expiration;

    @Column(name = "token_type", length = 50, nullable = false)
    private String tokenType;

    @Column(name = "session_uuid", length = 50, nullable = false)
    private String sessionUuid;

    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL, optional = false)
    @PrimaryKeyJoinColumn
    private BaseOAuth2RefreshToken refreshToken;

    @ElementCollection
    private Set<String> scope;

    @Transient
    private String key;

    @Transient
    private Map<String, Object> additionalInformation;

    protected BaseOAuth2AccessToken() {
        this.tokenType = "Bearer".toLowerCase();
        this.additionalInformation = new IdentityHashMap<>();
    }

    public BaseOAuth2AccessToken(final String value, final long interval) {
        this();
        this.expiration = DateTimeHelper.calcExpirationDate(Duration.ofSeconds(interval));
        this.value = HashGeneratorHelper.mixTwoString(value, this.expiration.toString());
    }

    public BaseOAuth2AccessToken(final BaseOAuth2AccessToken accessToken) {
        this();
        this.setValue(accessToken.getValue());
        this.setAdditionalInformation(accessToken.getAdditionalInformation());
        this.setRefreshToken(accessToken.getRefreshToken());
        this.setExpiration(accessToken.getExpiration());
        this.setScope(accessToken.getScope());
        this.setTokenType(accessToken.getTokenType());
    }

    public Map<String, Object> getAdditionalInformation() {
        return this.additionalInformation;
    }

    public void setAdditionalInformation(Map<String, Object> additionalInformation) {
        this.additionalInformation = new LinkedHashMap(additionalInformation);
    }

    public Set<String> getScope() {
        return this.scope;
    }

    public void setScope(Set<String> scope) {
        this.scope = scope;
    }

    @Nonnull
    public BaseOAuth2RefreshToken getRefreshToken() {
        return this.refreshToken;
    }

    public void setRefreshToken(@Nonnull BaseOAuth2RefreshToken refreshToken) {
        this.refreshToken = refreshToken;
    }

    @Nonnull
    public String getTokenType() {
        return this.tokenType;
    }

    public void setTokenType(@Nonnull String tokenType) {
        this.tokenType = tokenType;
    }

    public boolean isExpired() {
        return this.expiration != null && this.expiration.isAfter(DateTimeHelper.getLocalCurrentTime().toInstant(ZoneOffset.UTC));
    }

    @Nonnull
    public Instant getExpiration() {
        return this.expiration;
    }

    public void setExpiration(@Nonnull Instant expiration) {
        this.expiration = expiration;
    }

    public int getExpiresIn() {
        return this.expiration != null ? Long.valueOf(Duration.between(this.expiration, DateTimeHelper.getLocalCurrentTime().toInstant(ZoneOffset.UTC)).toMillis() / 1000L).intValue() : 0;
    }

    public void setExpiresIn(final long interval) {
        this.setExpiration(DateTimeHelper.calcExpirationDate(Duration.ofSeconds(interval)));
    }

    @Nonnull
    public String getValue() {
        return this.value;
    }

    public void setValue(@Nonnull String value) {
        this.value = value;
    }

    @Nonnull
    public String getSessionUuid() {
        return sessionUuid;
    }

    public void setSessionUuid(@Nonnull String sessionUuid) {
        this.sessionUuid = sessionUuid;
    }

    @PrePersist
    protected void ensureSessionUuidIsNotNull() {
        if (this.sessionUuid == null || this.sessionUuid.isBlank()) {
            this.sessionUuid = java.util.UUID.randomUUID().toString();
        }
    }

    @Nullable
    public int getCounter() {
        return counter;
    }

    public void setCounter(@Nullable final int counter) {
        this.counter = counter;
    }

    public void incrementCounter() {
        ++counter;
    }

    @Nullable
    public String getQuestion() {
        return this.question;
    }

    public void setQuestion(@Nullable final String question) {
        this.question = question;
    }

    @JsonValue
    @Nullable
    public String getAnswear() {
        return answear;
    }

    public void setAnswear(@Nullable final String answear) {
        this.answear = answear;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public long getKeyCreationTime() {
        return this.getCreationTime().toInstant().toEpochMilli();
    }

    public String getExtendedInformation() {
        return additionalInformation == null || additionalInformation.isEmpty() ? "" : additionalInformation.get("extended.info").toString();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        BaseOAuth2AccessToken that = (BaseOAuth2AccessToken) o;
        return Objects.equals(value, that.value) && Objects.equals(sessionUuid, that.sessionUuid);
    }

    @Override
    public int hashCode() {
        return Objects.hash(super.hashCode(), value, sessionUuid);
    }

    /**
     * Controls Java Serialization inside ObjectOutputStream for Access Tokens.
     * Prevents the 'value' field from affecting the calculated MD5 cryptographic digest.
     */
    private static final ObjectStreamField[] serialPersistentFields = {
            new ObjectStreamField("expiration", Instant.class),
            new ObjectStreamField("tokenType", String.class),
            new ObjectStreamField("sessionUuid", String.class),
            new ObjectStreamField("scope", java.util.Set.class)
    };

}