# =================================================================
# APACHE PEKKO CLUSTER SHARDING CONFIGURATION
# =================================================================

pekko {
  actor {
    provider = "cluster"
    serialization-bindings {
      "com.soaesps.aggregator.actor.CborSerializable" = jackson-cbor
    }
  }
  remote.artery {
    canonical {
      hostname = "127.0.0.1"
      port = 25520
    }
  }
  cluster {
    seed-nodes = ["pekko://soaesps-aggregator@127.0.0.1:25520"]
    sharding {
      passivate-idle-entity.after = 10m
      remember-entities = off
    }
  }
}
