package com.soaesps.auth.consumer;

import com.soaesps.auth.service.BaseUserDetailsService;
import com.soaesps.core.DataModels.transaction.InboxMessage;
import com.soaesps.core.dto.AuthRegistrationPayload;

import com.soaesps.core.repository.transaction.InboxMessageRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.kafka.support.Acknowledgment;
import org.springframework.kafka.support.KafkaHeaders;
import org.springframework.messaging.handler.annotation.Header;
import org.springframework.messaging.handler.annotation.Payload;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Listener component executing critical security registration events.
 * Implements the Inbox Pattern to achieve resilient exactly-once event processing.
 */
@Component
public class AuthRegistrationConsumer {

    private static final Logger logger = LoggerFactory.getLogger(AuthRegistrationConsumer.class);

    private final InboxMessageRepository inboxRepository;
    private final BaseUserDetailsService userDetailsService;

    public AuthRegistrationConsumer(InboxMessageRepository inboxRepository, BaseUserDetailsService userDetailsService) {
        this.inboxRepository = inboxRepository;
        this.userDetailsService = userDetailsService;
    }

    /**
     * Consumes security registration events, deduplicates them via the Inbox table,
     * executes business logic, and commits offsets manually.
     *
     * @param payload    the automatically deserialized AuthRegistrationPayload object
     * @param routingKey the Kafka partition key (username)
     * @param ack        the acknowledgment handle to commit the offset manually
     */
    @KafkaListener(
            topics = "auth-registration-events",
            groupId = "auth-service-group",
            containerFactory = "authListenerFactory"
    )
    public void consumeAuthEvent(
            @Payload AuthRegistrationPayload payload,
            @Header(KafkaHeaders.RECEIVED_KEY) String routingKey,
            Acknowledgment ack) {

        String messageId = payload.outboxMessageId(); // Unique ID generated by the Outbox Service
        logger.info("Received auth event. MessageId: {}, UserKey: {}", messageId, routingKey);

        try {
            // Check if the message has already been processed (Deduplication Step)
            if (inboxRepository.existsById(messageId)) {
                logger.warn("Inbox pattern trigger: Message with ID '{}' already processed. " +
                        "Skipping business logic and committing offset.", messageId);
                ack.acknowledge();
                return;
            }

            // Delegate to a transactional method that saves both business entities and the Inbox log
            processBusinessDataAndLogInbox(payload, messageId);

            // Securely advance the broker offset once data layer execution completes
            ack.acknowledge();
            logger.info("Successfully processed event and committed Kafka offset for message: {}", messageId);

        } catch (Exception e) {
            logger.error("Failed to process auth registration stream for message ID: {}. Delivery postponed.",
                    messageId, e);
            throw e; // Rethrow to enforce backoff strategy inside container factory
        }
    }

    /**
     * Executes business logic and registers the inbox tracking record in a single atomic database transaction.
     */
    @Transactional
    protected void processBusinessDataAndLogInbox(AuthRegistrationPayload payload, String messageId) {
        // Execute primary domain business adjustments
        logger.info("Persisting security credentials record for user: {}", payload.username());
        userDetailsService.createUserAccount(payload);

        // Explicitly write the tracking log inside the same transactional workspace
        InboxMessage inboxLog = new InboxMessage(messageId);
        inboxRepository.save(inboxLog);
    }
}
