package com.soaesps.auth.repository;

import com.soaesps.auth.service.security.AccessTokenFactory;
import com.soaesps.core.DataModels.security.BaseOAuth2AccessToken;
import com.soaesps.core.DataModels.security.BaseOAuth2RefreshToken;
import com.soaesps.core.Utils.audit.AuditHelper;
import org.hibernate.Hibernate;
import org.hibernate.proxy.HibernateProxy;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.mockito.MockedStatic;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import org.springframework.security.core.userdetails.User;
import org.springframework.security.core.userdetails.UserDetails;

import java.util.Collections;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mockStatic;

/**
 * Integration tests for {@link OAuth2TokenRepository} cooperating with {@link AccessTokenFactory}.
 * Inherits isolated database contexts from {@link BaseAuthRepositoryTest}.
 */
class OAuth2TokenRepositoryTest extends BaseAuthRepositoryTest {

    @Autowired
    private OAuth2TokenRepository oAuth2TokenRepository;

    @Autowired
    private TestEntityManager entityManager;

    private AccessTokenFactory tokenFactory;
    private UserDetails dummyUser;

    @BeforeEach
    void setUp() {
        // Initialize the factory instance with repository, default secret and 1-hour validity (3600 seconds)
        tokenFactory = AccessTokenFactory.getInstance(oAuth2TokenRepository, "test-secret-key", 3600L);

        dummyUser = new User("test_user_username", "secure_password", Collections.emptyList());
    }

    @Nested
    @DisplayName("Factory Token Persistence")
    class FactoryPersistenceTests {

        @Test
        @DisplayName("Should successfully persist AccessToken and cascade persist RefreshToken generated by the factory")
        void factoryCreatedToken_shouldPersistCorrectly() throws Exception {
            BaseOAuth2AccessToken accessToken;

            // Mock static AuditHelper to prevent NullPointerException from missing HTTP Servlet Contexts
            try (MockedStatic<AuditHelper> auditMock = mockStatic(AuditHelper.class)) {
                auditMock.when(AuditHelper::getClientIpAddressIfServletRequestExist).thenReturn("127.0.0.1");
                auditMock.when(() -> AuditHelper.getNumericIP(anyString())).thenReturn(2130706433L); // 127.0.0.1 as Long
                auditMock.when(AuditHelper::getClientUserName).thenReturn("test_user_username");

                // When: Generate tokens using your exact AccessTokenFactory logic
                accessToken = tokenFactory.createAccessToken(dummyUser);
            }

            assertThat(accessToken).isNotNull();
            BaseOAuth2RefreshToken refreshToken = accessToken.getRefreshToken();
            assertThat(refreshToken).isNotNull();

            // Persist AccessToken first through repository (which triggers cascade mapping if defined)
            BaseOAuth2AccessToken savedAccessToken = oAuth2TokenRepository.saveAndFlush(accessToken);
            Long sharedId = savedAccessToken.getId();
            assertThat(sharedId).isNotNull();
            String expectedRefreshTokenValue = savedAccessToken.getRefreshToken().getValue();

            // Align the shared identifiers for the RefreshToken to fulfill foreign key constraints
            refreshToken.setId(sharedId);

            // Re-save the graph through the repository to guarantee both rows exist in H2 database tables safely
            savedAccessToken = oAuth2TokenRepository.saveAndFlush(savedAccessToken);

            entityManager.clear();

            // Then: Retrieve access token from H2 by the mapped ID
            BaseOAuth2AccessToken retrieved = oAuth2TokenRepository.findById(sharedId).orElseThrow();
            assertThat(retrieved.getTokenType()).isEqualTo("bearer");
            BaseOAuth2RefreshToken refresh = entityManager.find(BaseOAuth2RefreshToken.class, sharedId);
            assertThat(refresh).isNotNull();
            String refreshValue = refresh.getValue();
            assertThat(refreshValue).isEqualTo(expectedRefreshTokenValue);
        }
    }

    @Nested
    @DisplayName("Custom Repository Queries")
    class CustomQueryTests {

        @Test
        @DisplayName("Should retrieve AccessToken from database using findByRefreshToken query lookup")
        void findByRefreshToken_shouldReturnValidAccessToken() throws Exception {
            BaseOAuth2AccessToken accessToken;

            try (MockedStatic<AuditHelper> auditMock = mockStatic(AuditHelper.class)) {
                auditMock.when(AuditHelper::getClientIpAddressIfServletRequestExist).thenReturn("127.0.0.1");
                auditMock.when(() -> AuditHelper.getNumericIP(anyString())).thenReturn(2130706433L);
                auditMock.when(AuditHelper::getClientUserName).thenReturn("test_user_username");

                accessToken = tokenFactory.createAccessToken(dummyUser);
            }

            BaseOAuth2RefreshToken generatedRefreshToken = accessToken.getRefreshToken();

            // Persist the token graph safely via the repository method instead of entityManager
            BaseOAuth2AccessToken savedAccessToken = oAuth2TokenRepository.saveAndFlush(accessToken);
            Long id = savedAccessToken.getId();

            generatedRefreshToken.setId(id);
            savedAccessToken = oAuth2TokenRepository.saveAndFlush(savedAccessToken);
            BaseOAuth2RefreshToken persistedRefreshToken = savedAccessToken.getRefreshToken();

            entityManager.clear();

            // When: Execute repository custom lookup method using the refresh token entity mapping
            Optional<BaseOAuth2AccessToken> foundToken = oAuth2TokenRepository.findByRefreshToken(persistedRefreshToken);

            // Then
            assertThat(foundToken).isPresent();
            assertThat(foundToken.get().getId()).isEqualTo(id);
            assertThat(foundToken.get().getValue()).isEqualTo(accessToken.getValue());
        }
    }

    @Nested
    @DisplayName("Factory Token Re-issuance")
    class TokenReissueTests {

        @Test
        @DisplayName("Should successfully re-issue an AccessToken when calling factory logic with valid RefreshToken")
        void reIssueAccessToken_shouldUpdateAndSaveNewToken() throws Exception {
            // 1. Force state values into Static AuditHelper fields
            // to prevent NullPointerException without using Byte Buddy/Mockito on Java 25
            try (MockedStatic<AuditHelper> audit = mockStatic(AuditHelper.class)) {
                // 1. Force state values into Static AuditHelper fields
                // to prevent NullPointerException without using Byte Buddy/Mockito on Java 25
                audit.when(AuditHelper::getClientIpAddressIfServletRequestExist).thenReturn("127.0.0.1");
                audit.when(() -> AuditHelper.getNumericIP(anyString())).thenReturn(2130706433L);
                audit.when(AuditHelper::getClientUserName).thenReturn("test_user_username");

                // 2. Generate a valid token graph natively using your factory instance
                AccessTokenFactory.AccessTokenFactoryImpl factoryImpl =
                        (AccessTokenFactory.AccessTokenFactoryImpl) tokenFactory;

                BaseOAuth2AccessToken generatedToken = factoryImpl.createAccessToken(dummyUser);
                assertThat(generatedToken).isNotNull();

                BaseOAuth2RefreshToken generatedRefreshToken = generatedToken.getRefreshToken();
                assertThat(generatedRefreshToken).isNotNull();

                // Ensure mandatory sessionUuid is present to prevent H2 NULL constraints failure
                if (generatedToken.getSessionUuid() == null) {
                    generatedToken.setSessionUuid(java.util.UUID.randomUUID().toString());
                }

                // 3. Persist the graph cleanly through the JPA repository into the database
                BaseOAuth2AccessToken savedAccessToken = oAuth2TokenRepository.saveAndFlush(generatedToken);
                Long tokenId = savedAccessToken.getId();

                generatedRefreshToken.setId(tokenId);
                savedAccessToken = oAuth2TokenRepository.saveAndFlush(savedAccessToken);
                oAuth2TokenRepository.flush();

                entityManager.clear();

                // 4. Retrieve the fresh token graph copy directly from the H2 session
                //BaseOAuth2AccessToken dbToken = oAuth2TokenRepository.findById(tokenId).orElseThrow();
                BaseOAuth2AccessToken dbToken = entityManager.find(BaseOAuth2AccessToken.class, tokenId);
                BaseOAuth2RefreshToken persistedRefreshToken = unproxy(entityManager.find(BaseOAuth2RefreshToken.class, tokenId));

                // When: Execute the actual public reissue logic natively
                BaseOAuth2AccessToken reIssuedToken = factoryImpl.reIssueAccessToken(persistedRefreshToken);

                // Then: The validation satisfies naturally, hits the repository and safely returns updated instance
                assertThat(reIssuedToken).isNotNull();
                assertThat(reIssuedToken.getId()).isEqualTo(tokenId);
            }
        }

        public static <T> T unproxy(T entity) {
            if (entity == null) {
                return null;
            }
            if (entity instanceof HibernateProxy) {
                Hibernate.initialize(entity); // Принудительно загружаем данные из БД
                return (T) ((HibernateProxy) entity).getHibernateLazyInitializer().getImplementation();
            }
            return entity;
        }
    }
}
