package com.nukefintech.uitoken.service;

import com.nukefintech.uitoken.domain.UiTokenLayout;
import com.nukefintech.uitoken.repository.UiTokenLayoutRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.cache.CacheManager;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Mono;

/**
 * Enterprise service layer managing server-driven UI design token models.
 * Integrates hot memory Caffeine caches straight over non-blocking reactive streams.
 */
@Service
public class UiTokenService {

    private static final Logger log = LoggerFactory.getLogger(UiTokenService.class);
    private static final String CACHE_NAME = "ui_layouts";

    private final UiTokenLayoutRepository repository;
    private final CacheManager cacheManager;

    public UiTokenService(UiTokenLayoutRepository repository, CacheManager cacheManager) {
        this.repository = repository;
        this.cacheManager = cacheManager;
    }

    /**
     * Resolves customized tokens framework configurations from memory maps.
     * Generates a sub-millisecond return speed loop under intense load spikes.
     */
    @Cacheable(value = CACHE_NAME, key = "#documentType.toUpperCase() + '_' + #viewMode.toUpperCase() + '_' + #density.toUpperCase()")
    public Mono<UiTokenLayout> resolveLayoutTokens(String documentType, String viewMode, String density) {
        String docTypeClean = documentType.toUpperCase();
        String viewModeClean = viewMode.toUpperCase();
        String densityClean = density.toUpperCase();

        log.info("[UI-Cache-Miss] Downloading design tokens configuration from MongoDB cluster for context: {} ({}/{})",
                docTypeClean, viewModeClean, densityClean);

        return repository.findByDocumentTypeAndViewModeAndDensity(docTypeClean, viewModeClean, densityClean)
                .cache(); // Memoizes signals upstream allocation chains inside the active JVM heap
    }

    /**
     * Persists or registers a modified design tokens package generated by the LLM agent.
     * Safely triggers programmatic eviction flush tasks over the active cache keys context.
     */
    public Mono<UiTokenLayout> saveLayout(UiTokenLayout layout) {
        String docTypeClean = layout.getDocumentType().toUpperCase();
        String viewModeClean = layout.getViewMode().toUpperCase();
        String densityClean = layout.getDensity().toUpperCase();

        layout.setDocumentType(docTypeClean);
        layout.setViewMode(viewModeClean);
        layout.setDensity(densityClean);

        String cacheKey = docTypeClean + "_" + viewModeClean + "_" + densityClean;
        log.info("[UI-Token-Mutation] Deploying updated design matrix profile block for cache address: {}", cacheKey);

        return repository.save(layout)
                .doOnSuccess(saved -> {
                    log.warn("[UI-Cache-Evict] Purging stale design layout cache key index token: {}", cacheKey);
                    var cache = cacheManager.getCache(CACHE_NAME);
                    if (cache != null) {
                        cache.evict(cacheKey); // Explicit thread-safe hot programmatic buffer wipe out
                    }
                });
    }
}