-- Dynamic schema initialization for full polymorphic user_contacts hierarchy
CREATE TABLE IF NOT EXISTS user_contacts (
    -- Base class shared fields (UserContact)
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    contact_type VARCHAR(50) NOT NULL,       -- JPA Discriminator column (EMAIL, SMS, TELEGRAM, PUSH)
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    is_primary BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- EmailContact specific properties
    email_address VARCHAR(255),

    -- SmsContact specific properties
    phone_number VARCHAR(20),

    -- TelegramContact specific properties
    telegram_chat_id VARCHAR(100),
    telegram_username VARCHAR(100),          -- Maps to "username" field in TelegramContact

    -- PushDeviceContact specific properties
    push_token VARCHAR(500),
    device_id VARCHAR(255),
    device_type VARCHAR(50)                  -- Keeps e.g., IOS, ANDROID, WEB strings
);

-- Optional performance optimization index for lightning-fast user channel lookups
CREATE INDEX IF NOT EXISTS idx_user_contacts_user_id ON user_contacts(user_id);
