-- Dynamic configuration dictionary for validating incoming event payloads
CREATE TABLE IF NOT EXISTS supported_notification_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(100) UNIQUE NOT NULL, -- e.g., 'PAYMENT_SUCCESS', 'SECURITY_ALERT'
    is_active BOOLEAN DEFAULT TRUE NOT NULL
);